services:
  postgres:
    container_name: alunos-postgres
    image: postgres:17
    environment:
      POSTGRES_USER: alunos_user
      POSTGRES_PASSWORD: alunos_password
      POSTGRES_DB: alunos_db
    ports:
      - "5432:5432"
    
    